spring.application.name=spring-boot-webflux-apirest
spring.data.mongodb.uri=mongodb://localhost:27017/spring_boot_webflux

configuracion.cargarimagenes.ruta = C:\\Users\\juan.arango\\Documents\\Udemy\\imagenes_proyecto_programacion_spring_webflux\\
